"""
Reporter - generates markdown reports from test results.
"""

import os
import json
from datetime import datetime, timezone
from typing import Optional


def generate_report(repo_owner: str, repo_name: str, repo_description: str,
                    stars: int, language: str, hn_title: str, hn_score: int,
                    install_results: list, analysis: dict,
                    experience: dict = None,
                    output_dir: str = "reports") -> str:
    """Generate a markdown report and save it to disk."""

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    slug = f"{repo_owner}-{repo_name}"
    filename = f"{slug}.md"

    # Build environment results table
    env_rows = []
    for r in install_results:
        status = "PASS" if r.success else "FAIL"
        env_rows.append(f"| {r.environment} | {status} | {r.total_duration}s |")
    env_table = "\n".join(env_rows)

    verdict = analysis.get("verdict", "unknown")
    difficulty = analysis.get("install_difficulty", "unknown")
    summary = analysis.get("summary", "")
    tips = analysis.get("tips", [])
    issues = analysis.get("issues", [])
    guide = analysis.get("step_by_step_guide", [])
    time_est = analysis.get("time_estimate", "unknown")

    tips_md = "\n".join(f"- {t}" for t in tips) if tips else "- None"
    issues_md = "\n".join(f"- {t}" for t in issues) if issues else "- None"
    guide_md = "\n".join(f"{i+1}. {step}" for i, step in enumerate(guide)) if guide else "No guide generated."

    # Build experience section
    if experience:
        exp_parts = []
        if experience.get("first_impression"):
            exp_parts.append(f"**First Impression:** {experience['first_impression']}")
        if experience.get("experience_summary"):
            exp_parts.append(f"\n{experience['experience_summary']}")
        if experience.get("what_i_tried"):
            exp_parts.append("\n**What I tried:**")
            for item in experience["what_i_tried"]:
                exp_parts.append(f"- {item}")
        if experience.get("pros"):
            exp_parts.append("\n**Pros:**")
            for p in experience["pros"]:
                exp_parts.append(f"- {p}")
        if experience.get("cons"):
            exp_parts.append("\n**Cons:**")
            for c in experience["cons"]:
                exp_parts.append(f"- {c}")
        if experience.get("who_is_this_for"):
            exp_parts.append(f"\n**Target user:** {experience['who_is_this_for']}")
        if experience.get("would_i_use_it"):
            exp_parts.append(f"\n**Would I use it?** {experience['would_i_use_it']}")
        if experience.get("rating"):
            exp_parts.append(f"\n**Rating:** {experience['rating']}/5")
        experience_md = "\n".join(exp_parts)
    else:
        experience_md = "*Usage testing was skipped (installation failed or not applicable).*"

    verdict_emoji = {"works": "PASS", "works_with_issues": "WARN", "broken": "FAIL"}.get(verdict, "?")

    report = f"""# First Look: {repo_owner}/{repo_name}

> {repo_description or 'No description'}

| Field | Value |
|-------|-------|
| Tested | {now} |
| Source | https://github.com/{repo_owner}/{repo_name} |
| HN Post | "{hn_title}" (score: {hn_score}) |
| Language | {language} |
| Stars | {stars} |
| Verdict | {verdict_emoji} {verdict} |
| Install Difficulty | {difficulty} |
| Estimated Human Time | {time_est} |

## Summary

{summary}

## Environment Results

| Environment | Status | Duration |
|-------------|--------|----------|
{env_table}

## Step-by-Step Installation Guide

{guide_md}

## Automated Usage Test

> *The following is AI-generated based on actual command execution in a Docker sandbox. Results may differ in your environment.*

{experience_md}

## Issues Found

{issues_md}

## Tips

{tips_md}

---
*Generated by [first-look](https://github.com/yaowubarbara/first-look) - AI tries new tools so you don't have to.*
"""

    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w") as f:
        f.write(report)

    print(f"[reporter] Report saved: {filepath}")
    return filepath


def generate_tweet(repo_owner: str, repo_name: str, verdict: str,
                   difficulty: str, summary: str, hn_url: str = "") -> str:
    """Generate a short tweet-sized summary."""
    verdict_map = {"works": "PASS", "works_with_issues": "~OK", "broken": "FAIL"}
    v = verdict_map.get(verdict, "?")

    tweet = f"First Look: {repo_owner}/{repo_name}\n\n"
    tweet += f"{summary[:180]}\n\n"
    tweet += f"Verdict: {v} | Difficulty: {difficulty}\n"
    tweet += f"https://github.com/{repo_owner}/{repo_name}"
    return tweet
